"""Fixed the job api receiver from frontend

Revision ID: 50a0b0555add
Revises: 998da261492e
Create Date: 2026-04-18 18:54:08.783210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a0b0555add'
down_revision = '998da261492e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ats_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('ats_score')

    # ### end Alembic commands ###
