"""Updated the job schema with status either open or close

Revision ID: 50e3a3cff9b5
Revises: 1a8c06e15932
Create Date: 2026-04-18 12:54:03.184895

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50e3a3cff9b5"
down_revision = "1a8c06e15932"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_candidates_job_id_jobs",
            "jobs",
            ["job_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("candidates", schema=None) as batch_op:
        batch_op.drop_constraint("fk_candidates_job_id_jobs", type_="foreignkey")
        batch_op.drop_column("job_id")

    # ### end Alembic commands ###
