"""add recruiter data to jobs

Revision ID: c220389a42a2
Revises: ab2cf455d3a8
Create Date: 2026-04-18 14:12:15.556732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c220389a42a2'
down_revision = 'ab2cf455d3a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recruiter_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('recruiter_data')

    # ### end Alembic commands ###
