"""Fixed the meeting summary db

Revision ID: f87109fe65cc
Revises: d84b7a9c11f2
Create Date: 2026-04-19 04:01:30.548847

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f87109fe65cc"
down_revision = "d84b7a9c11f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_summaries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_meeting_summaries_job_id_jobs",
            "jobs",
            ["job_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("meeting_summaries", schema=None) as batch_op:
        batch_op.drop_constraint("fk_meeting_summaries_job_id_jobs", type_="foreignkey")
        batch_op.drop_column("job_id")

    # ### end Alembic commands ###
