SKILL_KEYWORDS = {
    "javascript": [
        "javascript",
        "js",
        "node",
        "nodejs",
        "react",
        "vue",
        "angular",
        "typescript",
        "webpack",
        "babel",
        "npm",
        "express",
        "nextjs",
        "nuxt",
        "gatsby",
        "svelte",
        "redux",
        "jest",
        "mocha",
        "eslint",
        "jquery",
        "socket.io",
        "electron",
    ],
    "typescript": [
        "typescript",
        "ts",
        "angular",
        "nestjs",
        "deno",
        "tsx",
        "tsc",
    ],
    "python": [
        "python",
        "py",
        "django",
        "flask",
        "fastapi",
        "pandas",
        "numpy",
        "scipy",
        "matplotlib",
        "jupyter",
        "pip",
        "conda",
        "pytest",
        "celery",
        "sqlalchemy",
        "pydantic",
        "asyncio",
        "aiohttp",
    ],
    "rust": [
        "rust",
        "cargo",
        "rustlang",
        "tokio",
        "actix",
        "wasm",
        "webassembly",
        "serde",
        "axum",
        "bevy",
    ],
    "go": [
        "golang",
        "go",
        "gin",
        "echo",
        "fiber",
        "goroutine",
        "gorm",
        "grpc",
        "protobuf",
    ],
    "java": [
        "java",
        "spring",
        "maven",
        "gradle",
        "hibernate",
        "junit",
        "jvm",
        "kotlin",
        "springboot",
        "microservices",
    ],
    "c / c++": [
        "cpp",
        "c++",
        "cmake",
        "clang",
        "llvm",
        "arduino",
        "embedded",
        "qt",
        "makefile",
        "gcc",
        "opengl",
    ],
    "react": [
        "react",
        "jsx",
        "nextjs",
        "gatsby",
        "redux",
        "hooks",
        "vite",
        "react-native",
        "storybook",
        "tailwind",
    ],
    "docker / devops": [
        "docker",
        "dockerfile",
        "container",
        "compose",
        "kubernetes",
        "k8s",
        "helm",
        "devops",
        "ci/cd",
        "cicd",
        "github-actions",
        "circleci",
        "jenkins",
        "ansible",
        "terraform",
        "pulumi",
    ],
    "cloud": [
        "aws",
        "amazon",
        "lambda",
        "s3",
        "ec2",
        "gcp",
        "azure",
        "cloudformation",
        "serverless",
        "digitalocean",
        "heroku",
    ],
    "machine learning": [
        "tensorflow",
        "pytorch",
        "keras",
        "sklearn",
        "scikit-learn",
        "xgboost",
        "lightgbm",
        "machine learning",
        "deep learning",
        "neural network",
        "nlp",
        "transformers",
        "huggingface",
        "bert",
        "llm",
        "model training",
        "computer vision",
    ],
    "databases": [
        "sql",
        "postgres",
        "postgresql",
        "mysql",
        "mongodb",
        "redis",
        "elasticsearch",
        "sqlite",
        "prisma",
        "typeorm",
        "sequelize",
        "dynamodb",
        "cassandra",
        "supabase",
    ],
    "web3 / crypto": [
        "blockchain",
        "solidity",
        "ethereum",
        "web3",
        "nft",
        "defi",
        "smart contract",
        "hardhat",
        "truffle",
        "metamask",
        "solana",
    ],
    "mobile": [
        "swift",
        "ios",
        "android",
        "flutter",
        "dart",
        "react-native",
        "kotlin",
        "expo",
        "objective-c",
        "xcode",
    ],
    "data engineering": [
        "spark",
        "kafka",
        "airflow",
        "dbt",
        "etl",
        "pipeline",
        "bigquery",
        "snowflake",
        "databricks",
        "luigi",
        "prefect",
        "flink",
        "hadoop",
    ],
}
