SKILL_KEYWORDS = {
    "python": [
        "python",
        "django",
        "flask",
        "fastapi",
        "pandas",
        "numpy",
        "pytorch",
        "tensorflow",
        "scikit",
    ],
    "javascript": [
        "javascript",
        "js",
        "node",
        "nodejs",
        "react",
        "vue",
        "angular",
        "typescript",
        "next.js",
        "express",
    ],
    "java": ["java", "spring", "springboot", "maven", "gradle", "hibernate"],
    "go": ["golang", "go lang"],
    "rust": ["rust", "cargo"],
    "c++": ["c++", "cpp", "cmake"],
    "ruby": ["ruby", "rails", "sinatra"],
    "php": ["php", "laravel", "symfony"],
    "swift": ["swift", "swiftui", "ios", "xcode"],
    "kotlin": ["kotlin", "android"],
    "docker": ["docker", "dockerfile", "containerization", "docker-compose"],
    "kubernetes": ["kubernetes", "k8s", "kubectl", "helm"],
    "aws": ["aws", "amazon web services", "ec2", "s3", "lambda", "cloudformation"],
    "gcp": ["gcp", "google cloud", "bigquery", "gke"],
    "azure": ["azure", "microsoft azure"],
    "terraform": ["terraform", "hcl", "infrastructure as code"],
    "sql": ["sql", "mysql", "postgresql", "postgres", "sqlite", "oracle", "mssql"],
    "mongodb": ["mongodb", "mongo", "nosql", "mongoose"],
    "redis": ["redis", "caching", "cache"],
    "graphql": ["graphql", "apollo"],
    "git": ["git", "github", "gitlab", "version control"],
    "ci/cd": ["ci/cd", "github actions", "jenkins", "gitlab ci", "circleci", "travis"],
    "machine learning": [
        "machine learning",
        "ml",
        "deep learning",
        "neural network",
        "nlp",
        "computer vision",
    ],
    "data science": [
        "data science",
        "data analysis",
        "visualization",
        "tableau",
        "power bi",
    ],
    "linux": ["linux", "unix", "bash", "shell", "ubuntu", "debian"],
}

GITHUB_LANGUAGE_MAP = {
    "Python": "python",
    "JavaScript": "javascript",
    "TypeScript": "javascript",
    "Java": "java",
    "Go": "go",
    "Rust": "rust",
    "C++": "c++",
    "Ruby": "ruby",
    "PHP": "php",
    "Swift": "swift",
    "Kotlin": "kotlin",
    "Shell": "linux",
    "HCL": "terraform",
}

QUALITY_KEYWORDS = {"api", "backend", "system", "service", "engine"}
LIBRARY_MARKERS = {
    "library",
    "framework",
    "sdk",
    "cli",
    "toolkit",
    "plugin",
    "package",
    "module",
    "runtime",
    "lib",
}
EDUCATIONAL_MARKERS = {
    "freecodecamp",
    "course",
    "curriculum",
    "lesson",
    "lecture",
    "workshop",
    "homework",
    "assignment",
    "exercise",
    "solutions",
    "labs",
    "bootcamp",
}
TUTORIAL_MARKERS = {
    "100 days of code",
    "100-days-of-code",
    "100days",
    "clone",
    "demo",
    "tutorial",
    "beginner",
    "starter",
    "boilerplate",
    "practice",
    "leetcode",
}
REPO_TYPE_WEIGHTS = {
    "personal_project": 1.0,
    "library_or_framework": 0.7,
    "unknown": 0.3,
    "organization_repo": 0.2,
    "tutorial_or_clone": 0.1,
    "educational_content": 0.0,
}
STRUCTURE_MARKERS = {
    "src",
    "tests",
    "test",
    "docs",
    "doc",
    "modular",
    "monorepo",
    "architecture",
    "service",
    "api",
    "backend",
}
PACKAGE_MARKERS = {
    "package.json",
    "requirements.txt",
    "pyproject.toml",
    "setup.py",
    "pom.xml",
    "build.gradle",
    "cargo.toml",
    "go.mod",
    "composer.json",
    "dockerfile",
    "tsconfig.json",
    "vite.config",
    "webpack",
}
SIGNAL_WEIGHTS = {
    "language": 1.0,
    "topic": 0.6,
    "keyword": 0.3,
    "structure": 0.5,
}
REPO_SIGNAL_CAP = 1.0
EXCEPTIONAL_CONFIDENCE_THRESHOLD = 0.85
MIN_REPO_VIABILITY = 0.08
MIN_CONFIRMED_SIGNALS = 2
